#!/usr/bin/env python3
"""s01_overview.py — Step 1. What the corpus contains, how far its labels can be trusted, and what an
independent re-labelling (incident-rank-validation) found. NO dissection into ON-AI / WITH-AI here; where a
population appears (Tables 1.6, 1.13, 1.17) it is read from out/split.json, so run `make s02` once before
quoting those columns.

Section 0 prints the shared How-to-read note, the glossary and the two OWASP numberings every other file
points to. A checks the pinned package against the README's example calls. B profiles the full corpus and
defines the disclosure channel. B2 shows the corpus's own keyword labels. C reads rank-validation's
committed artifacts (never run). Output: out/s01_overview.md
"""
import collections, hashlib, json, re
from importlib.metadata import version
from genai_incidents import query, by_cve, resolve_id, load_incidents          # README example calls
from common import (load_full, load_rv, join_rv, load_prelabels, owasp_names, beta_mean, blind_agreement, source_class, table, write,
                    HOWTO, GLOSSARY, CHANNELS, EXT, OUT, CYCLE)

PINS = json.load(open(EXT / "PINS.json")); MERGE = (EXT / "corpus_merge_and_dedupe.py").read_text().splitlines()
pct = lambda a, b: f"{100*a/b:.1f}" if b else "—"
def defline(fn):
    """Line of `def fn(` in the corpus's build script (read only), so the output cites a confirmed location."""
    return next(i + 1 for i, l in enumerate(MERGE) if l.startswith(f"def {fn}("))
def vote_ci(path=CYCLE / "results/rank_comparison_report.md"):
    """Vote-rank 90% interval per entry from rank-validation's report (load_rv keeps only the point rank)."""
    pat = re.compile(r"^\|\s*([A-Z0-9-]+)\s*\|[^|]*\|\s*([\d.]+) \(([\d.]+)[–-]([\d.]+)\)")
    return {m.group(1): (float(m.group(3)), float(m.group(4))) for l in open(path) if (m := pat.match(l.strip()))}
def multi(num, title, field, names, desc):
    """Multi-label code table: one row per code with its name, assignments, share of assignments and of records, and
    the share of each channel's records carrying it."""
    c = collections.Counter(x for r in R for x in (r.get(field) or [])); tot = sum(c.values())
    L = ["", f"**Table {num}. {title}** (n = {tot:,} assignments on {sum(bool(r.get(field)) for r in R):,} records)", "", desc, "",
         "| code | name | n | % of assignments | % of records |" + "".join(f" % in {x} |" for x in CHANNELS), "|---|---|---|---|---|" + "---|" * len(CHANNELS)]
    for k, v in c.most_common():
        L.append(f"| {k} | {names.get(k, '?')} | {v:,} | {pct(v, tot)} | {pct(v, n)} |" + "".join(f" {pct(sum(k in (r.get(field) or []) for r in CH[x]), len(CH[x]))} |" for x in CHANNELS))
    return L

C = load_full(); R = list(C.values()); n = len(R)
CH = {x: [r for r in R if source_class(r) == x] for x in CHANNELS}
rv = load_rv(); NM = owasp_names(rv)
SPLIT = json.load(open(OUT / "split.json")) if (OUT / "split.json").exists() else None
popc = lambda ids: ", ".join(f"{p} {v:,}" for p, v in collections.Counter(SPLIT[i]["population"] for i in ids).most_common()) if SPLIT else "— (run `make s02`, then `make s01` again)"

L = ["# Step 1 — What the corpus contains, and what an earlier independent re-labelling found", "",
     f"Inputs: genai-incidents {version('genai-incidents')}, full JSON sha256 {PINS['incidents_json_sha256'][:12]}…, incident-rank-validation commit "
     f"{PINS['incident_rank_validation_commit'][:12]}, ATLAS {PINS['atlas_release']} commit {PINS['atlas_data_commit'][:12]}; "
     f"`out/split.json` (step 2, read for the population columns) {'sha256 ' + hashlib.sha256((OUT / 'split.json').read_bytes()).hexdigest()[:12] + '…' if SPLIT else 'absent: run `make s02`, then `make s01` again'}. "
     "Generated by `s01_overview.py` (`make s01`); do not edit by hand."]

# ---------------- 0. shared conventions
guide = {m.group(1): m.group(2).strip() for l in open(EXT / "incident-rank-validation/docs/GOLDSET-LLM-ADJUDICATION-GUIDE.md")
         if (m := re.match(r"^\|\s*((?:LLM\d\d|NEW-[A-Z]+|ROLL-[A-Z]+))\s*\|\s*([^|]+)\|", l))}
stale = [(e, guide[e]) for e in rv["taxonomy"] if e in guide and guide[e].lower() != rv["taxonomy"][e]["canonical_name"].lower()]
differ = sum(c != e for e, c in NM["rv2corpus"].items())
L += ["", "## 0. How to read every file in `out/`", "", HOWTO, "", "**Glossary.** Terms used in every step; each is defined once, here.", ""]
L += [f"- **{t}** — {d}" for t, d in GLOSSARY]
L += ["", f"**Table 1.0. The two OWASP numberings: the same ten entries, {differ} of them with a different code in the corpus and in rank-validation, plus the ten proposed additions** (n = {len(rv['taxonomy'])} entries)", "",
      "The corpus and rank-validation number the OWASP LLM Top 10 (2026) differently, so every join in this study is by name and every table prints the name. "
      "The ten proposed additions exist only in rank-validation's candidate list and have no corpus code.", "",
      "| name | corpus code | rank-validation id |", "|---|---|---|"]
L += [f"| {NM['rv'][e]}{'' if NM['rv'][e].lower() == NM['corpus'][c].lower() else ' (corpus name: ' + NM['corpus'][c] + ')'} | {c} | {e} |" for c in sorted(NM["corpus"]) for e in [NM["corpus2rv"][c]]]
L += [f"| {NM['rv'][e]} | — | {e} |" for e in sorted(e for e in rv["taxonomy"] if e not in NM["rv2corpus"])]
if stale: L += ["", f"*Names are rank-validation's taxonomy names and section C uses them throughout; where the corpus's own name differs it follows in parentheses, and section B2 "
                    f"(the corpus's labels) uses the corpus's names. The quick-reference table in its adjudication guide (`docs/GOLDSET-LLM-ADJUDICATION-GUIDE.md`) gives a different "
                    f"name for {len(stale)} of these {len(guide)} entries (e.g. {stale[0][0]} \"{stale[0][1]}\"), so that table is stale and is not used.*"]

# ---------------- A. README example calls
hits = list(query(severity="Critical", attack_vector="prompt-injection", year=2026)); pkg = load_incidents()
retracted = [r for r in R if r.get("status") == "retracted"]; reasons = {f"{(r.get('status_reason') or {}).get('code')} as of {(r.get('status_reason') or {}).get('as_of')}" for r in retracted}
L += ["", "## A. Check: the pinned package answers the README's example calls", "", "```",
      f'query(severity="Critical", attack_vector="prompt-injection", year=2026) -> {len(hits)} records',
      f'by_cve("CVE-2026-21520") -> {[i["id"] for i in by_cve("CVE-2026-21520")]}',
      f'resolve_id("INC-00139") -> {resolve_id("INC-00139")}', "```", "",
      f"The package's `load_incidents()` and the pinned JSON hold the same {n:,} ids ({'identical' if {r['id'] for r in pkg} == set(C) else 'DIFFERENT'} id sets). "
      f"The README's headline count is {n - len(retracted):,}: it excludes the {len(retracted)} records with `status == 'retracted'` "
      f"({'; '.join(sorted(reasons))}), which the pinned file retains and which stay in every table below."]

# ---------------- B. corpus profile
S = [s for r in R for s in r["source_ids"]]; early = sum(r["year"] < 2019 for r in R); merged = sum(len(r["source_ids"]) > 1 for r in R)
med = lambda xs: sorted(xs)[len(xs) // 2]; dlen = lambda rs: med([len(r.get("description") or "") for r in rs])
cwe_only = [r for r in R if r.get("cwe_ids") and not r.get("cve_ids")]
prefix = lambda s: re.match(r"[A-Za-z]*", s).group(0) or s
L += ["", f"## B. What the data is: {n:,} records from two kinds of tracker", "",
      f"- Records: **{n:,}**, dated {min(r['year'] for r in R)}–{max(r['year'] for r in R)}; {len(retracted)} are retracted but retained.",
      f"- With a CVE: {sum(bool(r.get('cve_ids')) for r in R):,}; with a CWE: {sum(bool(r.get('cwe_ids')) for r in R):,}; CWE but no CVE: {len(cwe_only):,} "
      f"({'all' if all(any(s.startswith('GHSA') for s in r['source_ids']) for r in cwe_only) else 'mostly'} GHSA advisories).",
      f"- Merged from several trackers: {merged:,}.",
      f"- Median description {dlen(R)} characters (cve/ghsa {dlen(CH['cve/ghsa'])}, harm-db {dlen(CH['harm-db'])}, research/other {dlen(CH['research/other'])}): "
      "enough to find and stratify a record, not to code how an attack happened, which is why the corpus is a sampling frame and not coding material."]
pc = collections.Counter(prefix(s) for s in S)
L += table(f"Which trackers the records come from: CVE/GHSA {pct(pc['CVE']+pc['GHSA'], len(S))}% of source ids, four harm databases "
           f"{pct(pc['OECD']+pc['AIAAIC']+pc['AIID']+pc['AVID'], len(S))}%", S, prefix, num="1.1",
           desc=f"Source ids by tracker prefix; a record merged from several trackers carries several ids, so n counts ids, not records. "
                "Prefix key: CVE, GHSA vulnerability feeds; OECD, AIAAIC, AIID, AVID harm databases; PROMPTFOO, GARAK red-team tool output; "
                f"ARXIV and conference prefixes (USENIX, NDSS, CCS) mark papers; INC, RES, EXT, VTR, LEGACY the corpus's own curated or reviewed entries (build script `_classify_quality_tier`, line {defline('_classify_quality_tier')}).")
agree = sum((source_class(r) == "cve/ghsa") == (r["category"] == "vulnerability-disclosure") for r in R)
L += ["", "### The disclosure channel: this study's one derived variable"]
L += table(f"Disclosure channel (this study's key grouping): {pct(len(CH['cve/ghsa']), n)}% CVE/GHSA, {pct(len(CH['harm-db']), n)}% harm databases, "
           f"{pct(len(CH['research/other']), n)}% research", R, source_class, num="1.2",
           desc="One channel per record (`common.source_class`): `cve/ghsa` if the record has a CVE id or a CVE/GHSA source id, else `harm-db` if it has an OECD, AIID, "
                "AIAAIC or AVID source id, else `research/other`; first match wins, so a record in both a CVE feed and a harm database counts as `cve/ghsa`. "
                f"It agrees with the corpus's record type (vulnerability disclosure ⇔ cve/ghsa) on {pct(agree, n)}% of records ({agree:,}), so later steps use the channel only.")
xt = collections.Counter((r["category"], source_class(r)) for r in R); cat = collections.Counter(r["category"] for r in R)
L += table(f"Record type (corpus `category`): {pct(cat['vulnerability-disclosure'], n)}% vulnerability disclosures, {pct(cat['real-world'], n)}% real-world incidents",
           R, lambda r: r["category"], num="1.3", channels=True,
           desc=f"The corpus's record type, one per record, with the share of each channel's records it covers. Cross-tab with channel: {xt[('vulnerability-disclosure','harm-db')]} "
                f"vulnerability disclosures are harm-db and {xt[('real-world','cve/ghsa')]} real-world records are cve/ghsa.")

land = [r for r in R if r["tier"] == "landmark"]; cur = [r for r in R if r["quality_tier"] == "curated"]; harm = [r for r in R if r.get("corpus") == "ai-harm"]
RULE = {("tier", "landmark"): "quality tier curated, or an AI Incident Database id, or corpus ai-harm", ("tier", "feed"): "every other record",
        ("quality_tier", "curated"): "a LEGACY entry, or a filled `mitigations` list with two or more sources",
        ("quality_tier", "reviewed"): "a maintained-catalogue source (OECD, AIID, AVID, ATLAS, RES, INC, VTR, …), a hand-picked AIAAIC entry, or a CVSS-scored CVE",
        ("quality_tier", "auto"): "an unscored CVE pull, the AIAAIC bulk sheet, PROMPTFOO or GARAK",
        ("corpus", "ai-harm"): "no CVE, no security keyword, and a fairness keyword in title, description or tags", ("corpus", "security"): "every other record (security wins ties)"}
L += ["", f"**Table 1.4. Curation flags are rules, not editorial choices: {pct(len(land), n)}% landmark, {pct(len(cur), n)}% curated, {pct(len(harm), n)}% ai-harm** (n = {n:,}; each block sums to 100)", "",
      f"Three one-value flags, each set by a rule in the corpus's build script (`_derive_tier` line {defline('_derive_tier')}, `_classify_quality_tier` line {defline('_classify_quality_tier')}, "
      f"`_classify_corpus` line {defline('_classify_corpus')}); the rule column paraphrases the code. Because of these rules {sum(source_class(r)=='harm-db' for r in land):,} of {len(land):,} landmark "
      f"records are harm-db, {sum(r['quality_tier']=='auto' for r in land)} landmark records are quality `auto`, {sum(r['tier']=='landmark' for r in cur)} of {len(cur)} curated records are landmark, "
      f"and {sum(r.get('corpus')=='security' for r in CH['harm-db']):,} of {len(CH['harm-db']):,} harm-database records are corpus `security`.", "",
      "| flag | value | rule | n | % |", "|---|---|---|---|---|"]
for f, key in (("tier", lambda r: r["tier"]), ("quality_tier", lambda r: r["quality_tier"]), ("corpus", lambda r: r.get("corpus"))):
    L += [f"| {f} | {k} | {RULE[(f, k)]} | {v:,} | {pct(v, n)} |" for k, v in collections.Counter(key(r) for r in R).most_common()]

Y = [r for r in R if r["year"] >= 2019]; yc = collections.Counter(r["year"] for r in Y); hy = collections.Counter(r["year"] for r in CH["harm-db"])
sh26 = {x: pct(sum(r["year"] == 2026 for r in CH[x]), sum(r["year"] >= 2019 for r in CH[x])) for x in CHANNELS}
L += table(f"Record year: 2026 holds {pct(yc[2026], len(Y))}% of records because of catch-up ingestion, not a trend", Y, lambda r: r["year"], top=10, by_value=True, num="1.5", channels=True,
           desc=f"Records dated 2019 or later ({early:,} earlier records, {min(r['year'] for r in R)}–2018, are left out); the channel columns give the share of each channel's 2019+ records in that year. "
                f"2026 is {sh26['cve/ghsa']}% of cve/ghsa, {sh26['harm-db']}% of harm-db and {sh26['research/other']}% of research/other records, and the 2020 peak and 2022 dip "
                f"are harm-database coverage ({hy[2020]:,} vs {hy[2022]:,}), so the table describes the frame, not the world; every later year table points here.")

months = sorted({str(r["added"])[:7] for r in R}); byM = {m: [r for r in R if str(r["added"])[:7] == m] for m in months}
last = byM[months[-1]]; dates = lambda rs: sorted({str(r["added"])[:10] for r in rs}); latest = lambda rs, x: max((str(r["date"]) for r in rs if source_class(r) == x), default="—")
L += ["", f"**Table 1.6. Ingestion cohorts: {len(months)} added-months ({len(dates(R))} `added` dates); harm-database records stop at {latest(R, 'harm-db')[:7]}, CVE records run to {latest(R, 'cve/ghsa')[:7]}** (n = {n:,})", "",
      f"Records by the month of the corpus `added` field (the build script stamps it with the UTC date a record first appears and keeps it afterwards, `_apply_history` line {defline('_apply_history')}, "
      f"and copies it to `first_seen` on {sum(r.get('first_seen') == r.get('added') for r in R):,} of {n:,} records), with the share dated 2026, the adversary-frame records (ON-AI + WITH-AI + BOTH, from step 2) "
      f"and the latest record date per channel. The {months[-1]} cohort ({len(dates(last))} date{'s' if len(dates(last)) > 1 else ''}, {', '.join(dates(last))}) added {sum(source_class(r)=='cve/ghsa' for r in last):,} CVE/GHSA records but "
      f"{sum(source_class(r)=='harm-db' for r in last)} harm-db records, none dated after {latest(last, 'harm-db')}.", "",
      "| added month | records | `added` dates | % dated 2026 | adversary-frame records | latest harm-db date | latest cve/ghsa date |", "|---|---|---|---|---|---|---|"]
for m in months:
    rs = byM[m]; fr = [r["id"] for r in rs if SPLIT and SPLIT[r["id"]]["population"] in ("ON-AI", "WITH-AI", "BOTH")]
    L.append(f"| {m} | {len(rs):,} | {len(dates(rs))} | {pct(sum(r['year']==2026 for r in rs), len(rs))} | {f'{len(fr):,} ({pct(len(fr), len(rs))}%)' if SPLIT else popc([])} | {latest(rs, 'harm-db')} | {latest(rs, 'cve/ghsa')} |")

prec = lambda rs: collections.Counter({10: "day", 7: "month", 4: "year"}.get(len(str(r["date"])), "other") for r in rs); pa = prec(R)
L += ["", f"**Table 1.7. Date precision is a channel property: CVE records month-only ({pct(prec(CH['cve/ghsa'])['month'], len(CH['cve/ghsa']))}%), harm databases day-level "
          f"({pct(prec(CH['harm-db'])['day'], len(CH['harm-db']))}%)** (n = {n:,})", "",
      f"Records by the precision of the corpus `date` field (YYYY-MM-DD, YYYY-MM or YYYY) within each channel. Corpus-wide: day {pct(pa['day'], n)}%, month {pct(pa['month'], n)}%, "
      f"year-only {pct(pa['year'], n)}%, so the two populations of step 2 cannot share a time axis finer than a year (Table 2.10).", "",
      "| channel | n | day % | month % | year-only % |", "|---|---|---|---|---|"]
L += [f"| {x} | {len(CH[x]):,} | {pct(prec(CH[x])['day'], len(CH[x]))} | {pct(prec(CH[x])['month'], len(CH[x]))} | {pct(prec(CH[x])['year'], len(CH[x]))} |" for x in CHANNELS]
L += [f"| *all records* | {n:,} | {pct(pa['day'], n)} | {pct(pa['month'], n)} | {pct(pa['year'], n)} |"]

# ---------------- B2. corpus labels
av = collections.Counter(r.get("attack_vector") or "other" for r in R)
L += ["", "## B2. Corpus labels (keyword rules): what the corpus's rules matched, not prevalence", "",
      "Every label in this section was assigned by the corpus's own keyword rules, not by a person (section 0); this study uses them to stratify samples and never as a coded field."]
L += table(f"Attack vector (corpus label): {pct(av['other'], n)}% 'other'; rce ({pct(av['rce'], n)}%) outranks prompt-injection ({pct(av['prompt-injection'], n)}%), the largest AI-specific vector",
           R, lambda r: r.get("attack_vector") or "other", top=15, num="1.8",
           desc=f"One value per record, {len(av)} values; `other` is the corpus's own value, distinct from the pooled row. AI-specific vectors are small (prompt-injection {pct(av['prompt-injection'], n)}%, "
                f"jailbreak {pct(av['jailbreak'], n)}%, model-poisoning {pct(av['model-poisoning'], n)}%) and the field mixes mechanisms (rce, xss) with harm types (deepfake, misinformation), "
                "which is why step 2 splits records by rule rather than by this field.")
sev = collections.Counter(r["severity"] for r in R); cvss = [r for r in R if r.get("cvss_score") is not None]; nocv = collections.Counter(source_class(r) for r in R if r.get("cvss_score") is None)
L += table(f"Severity (corpus label): {pct(sev['High']+sev['Critical'], n)}% High or Critical, but only {len(cvss):,} records have a CVSS score behind it",
           R, lambda r: r["severity"], num="1.9", channels=True,
           desc=f"One value per record. The {n-len(cvss):,} records without a CVSS score (harm-db {nocv['harm-db']:,}, research/other {nocv['research/other']:,}, cve/ghsa {nocv['cve/ghsa']:,}) "
                f"get their severity from a keyword rule that emits Low on {sum(r['severity']=='Low' for r in CH['harm-db'])} of {len(CH['harm-db']):,} harm-database records, so severity is not comparable across channels.")
ol = collections.Counter(c for r in R for c in (r.get("owasp_llm") or [])); cve = CH["cve/ghsa"]
sc = sum("LLM04" in (r.get("owasp_llm") or []) for r in cve); only = sum(bool(r.get("owasp_llm")) and set(r["owasp_llm"]) <= {"LLM04", "LLM10"} for r in cve)
mis_ch = collections.Counter(source_class(r) for r in R if "LLM07" in (r.get("owasp_llm") or [])); cov = {x: pct(sum(bool(r.get("owasp_llm")) for r in CH[x]), len(CH[x])) for x in CHANNELS}
top2 = ol.most_common(2)
L += multi("1.10", f"OWASP LLM codes the corpus assigned, with names: {NM['corpus'][top2[0][0]]} and {NM['corpus'][top2[1][0]]} on {pct(top2[0][1]+top2[1][1], sum(ol.values()))}% of assignments", "owasp_llm", NM["corpus"],
           f"Corpus numbering (Table 1.0); a record can carry several codes, so n counts assignments and the channel columns give the share of each channel's records carrying the code. "
           f"{NM['corpus']['LLM04']} sits on {pct(sc, len(cve))}% of CVE/GHSA records ({sc:,} of {len(cve):,}; {pct(only, len(cve))}% carry nothing but LLM04 and/or LLM10) and arrives with the upstream feed, "
           f"so on that channel it marks the channel, not the content; {NM['corpus']['LLM07']} is harm-db on {mis_ch['harm-db']:,} of {ol['LLM07']:,} assignments; "
           f"coverage is {cov['cve/ghsa']}% of cve/ghsa, {cov['harm-db']}% of harm-db and {cov['research/other']}% of research/other records.")
asi = collections.Counter(c for r in R for c in (r.get("owasp_asi") or [])); co = lambda a, l: sum(l in (r.get("owasp_llm") or []) for r in R if a in (r.get("owasp_asi") or []))
L += multi("1.11", f"OWASP Agentic (ASI) codes the corpus assigned, with names: they mirror the LLM codes ({pct(co('ASI04','LLM04'), asi['ASI04'])}% of {NM['asi']['ASI04']} records also carry {NM['corpus']['LLM04']})", "owasp_asi", NM["asi"],
           f"Same layout as Table 1.10 for the OWASP Agentic (ASI) Top 10; the ASI codes track the LLM codes record by record ({pct(co('ASI04','LLM04'), asi['ASI04'])}% of ASI04 records also carry LLM04, "
           f"{pct(co('ASI05','LLM10'), asi['ASI05'])}% of ASI05 records carry LLM10), so {sum(bool(r.get('owasp_asi')) for r in R):,} records carry an \"agentic\" code whatever their content. "
           "Kept because step 5's corpus lookup consumes ASI codes.")
cw = collections.Counter(c for r in R for c in (r.get("cwe_ids") or [])); t10 = cw.most_common(10)
L += table(f"Weakness ids (CWE): conventional web weaknesses lead; the prompt-injection weakness CWE-1427 appears {cw['CWE-1427']} times",
           [c for r in R for c in (r.get("cwe_ids") or [])], lambda c: c, top=10, num="1.12",
           desc=f"CWE (Common Weakness Enumeration) ids attached to records, nearly all inherited from CVE and GHSA entries; n counts the {sum(cw.values()):,} assignments on "
                f"{sum(bool(r.get('cwe_ids')) for r in R):,} records and the ten ids shown cover {pct(sum(v for _, v in t10), sum(cw.values()))}% of them. "
                f"CWE-1427 (prompt injection) is on {sum('CWE-1427' in (r.get('cwe_ids') or []) for r in R)} records, so CWE cannot identify AI-specific attacks and serves only as the \"software vulnerability present\" flag in step 4.")

# ---------------- C. incident-rank-validation artifacts
J = join_rv(C, rv); JR = J["rows"]; G = rv["gold"]; P = load_prelabels(); unres = set(J["unresolved"]); post = rv["posteriors"]; conc = rv["concordance"]
snap = json.load(open(CYCLE / "results/corpus_b_corroboration.json"))["corpus_a_incident_count"]
status = next((m.group(1) + " " + m.group(2).strip() for l in open(CYCLE / "results/report.md") if (m := re.match(r"\*\*STATUS: (.*?)\*\*\s*(.*)", l.strip()))), "")
mn = lambda x: f"{x:.2f}".replace("-", "−")
blind = sorted(e for e, x in json.load(open(CYCLE / "calibration/diagnostic.json"))["entry_reports"].items() if "frame-blind" in x["reason"])
hand = {i: r for i, r in JR.items() if r["gold_labels"] is not None}; noent = [i for i, r in hand.items() if r["gold_labels"] == []]
n_oos = sum(g["labels"] == [] for g in G.values()); gold_landed = sum(i in G for r in JR.values() for i in r["snapshot_ids"])
harm_tp = [(int(x["alpha"] - 1), int(x["alpha"] + x["beta"] - 2)) for k, x in post["recall"].items() if k.endswith("::ai-harm")]
name = lambda e: f"{NM['rv'][e]} ({'corpus ' + NM['rv2corpus'][e] + ' / ' if e in NM['rv2corpus'] else ''}rank-validation {e})"
L += ["", "## C. What an independent labelling of these records found (incident-rank-validation; artifacts read, never run)", "",
      "This study uses rank-validation's artifacts for three things only: excluding records the person judged to fit no entry, seeding hand-coding samples, and setting "
      f"expectations about where the OWASP community vote and incident data disagree; never for a cross-entry prevalence claim. Its 2026 cycle marks itself {status}; "
      f"its vote-vs-data agreement is weighted κ = {mn(conc['weighted_kappa_median'])} (interval {mn(conc['weighted_kappa_ci'][0])} to {mn(conc['weighted_kappa_ci'][1])}) over "
      f"{conc['measurable_count']} of {conc['total_count']} entries; and its `corpus = ai-harm` records are uncalibrated (recall sample of {min(t for _, t in harm_tp)}{'' if len({t for _, t in harm_tp}) == 1 else '–' + str(max(t for _, t in harm_tp))} rows per entry: "
      f"{sum(tp == 0 for tp, _ in harm_tp)} of {len(harm_tp)} entries with no true positive, the rest with {min(tp for tp, _ in harm_tp if tp)}–{max(tp for tp, _ in harm_tp)}; "
      f"{sum(k.endswith('::ai-harm') for k in post['precision'])} precision measurements)."]

cls = list(JR); ids_res = len(rv["labels"]) - len(unres); frame = [i for i in cls if SPLIT and SPLIT[i]["population"] in ("ON-AI", "WITH-AI", "BOTH")]
L += ["", f"**Table 1.13. What was labelled and what joins: snapshot {snap:,} → labelled {len(rv['labels']):,} → {len(JR):,} current records; hand-labelled {len(G):,} → {len(hand):,}** (n = {snap:,} snapshot records)", "",
      "Two chains: rank-validation's classifier labels, then its hand labels, from the May 2026 snapshot to the current corpus (ids followed through the package's redirects). "
      "Several snapshot ids can land on one current record because the corpus has merged duplicates since; a record keeps its own hand label where it has one.", "",
      "| step | rows | note |", "|---|---|---|",
      f"| snapshot records | {snap:,} | May 2026 |",
      f"| with a classifier label | {len(rv['labels']):,} | keyword rules {sum(r['rv_stage']==1 for r in JR.values()):,}, LLM {sum(r['rv_stage']==2 for r in JR.values()):,} on joined records |",
      f"| resolve to a current id | {ids_res:,} | {len(unres):,} do not |",
      f"| distinct current records | {len(JR):,} | {J['collapsed']:,} ids collapse onto already-counted records |",
      f"| … by population | {len(JR):,} | {popc(cls)} |",
      f"| … in the adversary frame | {len(frame):,} | {pct(len(frame), len(JR))}% of what the data rank is built on; {pct(len(frame), snap)}% of the snapshot |" if SPLIT else f"| … in the adversary frame | — | {popc([])} |",
      f"| hand-labelled rows | {len(G):,} | {n_oos:,} judged no entry fits |",
      f"| resolve to a current id | {len(G) - sum(i in unres for i in G):,} | {sum(i in unres for i in G)} do not |",
      f"| distinct hand-labelled records | {len(hand):,} | {gold_landed - len(hand)} ids collapse; {len(noent):,} of the {n_oos:,} no-entry rows join |",
      f"| … by population | {len(hand):,} | {popc(hand)} |",
      f"| … by channel | {len(hand):,} | {', '.join(f'{x} {v:,}' for x, v in collections.Counter(source_class(C[i]) for i in hand).most_common())} |"]

tiers = (("agree", "three pre-labellers agree"), ("split", "two agree"), ("disagree", "no majority"))
pool = collections.Counter(p["triage_tier"] for p in P.values()); gt = collections.Counter(P[i]["triage_tier"] for i in G)
cell = lambda ids: (len(ids), sum(G[i]["labels"] == [] for i in ids), sum(P[i]["agreement"] == "3-of-3" for i in ids), sum(P[i]["agreement"] == "2-of-3" for i in ids))
cap = max(cell([i for i in G if P[i]["consensus"] == e])[k] for e in rv["taxonomy"] for k in (2, 3)); _, _, oos_u, oos_m = cell([i for i in G if P[i]["consensus"] == "out-of-scope"])
blind_ok = blind_agreement(rv)[0]
samp = {i for s in json.load(open(CYCLE / "calibration/samples.json"))["samples"] for i in s["incident_ids"]}
L += ["", f"**Table 1.14. How the hand-labelled set was drawn: a quota on the LLM pre-labellers' consensus, not a random sample ({len(G):,} of {len(P):,} pre-labelled records)** (n = {len(P):,} pre-labelled records)", "",
      f"Rows are the cells of rank-validation's three-LLM pre-labelling (by how far the three agreed, then by the entry they agreed on): every no-majority row was taken, at most {cap} unanimous + {cap} majority rows per entry, "
      f"and {oos_u} + {oos_m} rows whose majority was 'no entry'. For each cell: records in the pool, how many were hand-labelled, the share taken, and how many the person judged to fit no entry; "
      "use these counts to see where the sample came from, never as a prevalence.", "",
      "| cell | pre-labelled records | hand-labelled (3-of-3 + 2-of-3) | % taken | no entry fits | % of hand-labelled |", "|---|---|---|---|---|---|"]
for t, lab in tiers:
    ids = [i for i in G if P[i]["triage_tier"] == t]; h, o, u, m = cell(ids)
    L.append(f"| tier: {lab} | {pool[t]:,} | {h:,} | {pct(h, pool[t])} | {o:,} | {pct(o, h)} |")
cons = collections.Counter(p["consensus"] for p in P.values() if p["consensus"])
for e, pn in sorted(cons.items(), key=lambda kv: -kv[1]):
    ids = [i for i in G if P[i]["consensus"] == e]; h, o, u, m = cell(ids)
    lab = "majority: no entry (LLM pre-label)" if e == "out-of-scope" else f"consensus: {NM['rv'][e]}"
    L.append(f"| {lab} | {pn:,} | {h:,} ({u} + {m}) | {pct(h, pn)} | {o:,} | {pct(o, h)} |")
L += ["", f"*Only {len(samp & set(G))} of the {len(G):,} hand-labelled rows appear in rank-validation's `calibration/samples.json`; the person's blind label (before seeing the three LLM votes) "
          f"equals the final label on {blind_ok:,} rows ({pct(blind_ok, len(G))}%).*"]

vci = vote_ci(); flags = {f["entry_id"]: f for f in conc["flags"]}; wide = sum(x["lambda_ci"][1] - x["lambda_ci"][0] >= 10 for e, x in rv["ranks"].items() if e not in blind)
wide_all = sum(x["lambda_ci"][1] - x["lambda_ci"][0] >= 10 for x in rv["ranks"].values())
act = collections.Counter(r["action"] for r in rv["ranks"].values())
L += ["", f"**Table 1.15. Where the community vote and rank-validation's data rank disagree, with that project's verdict: {act['review']} of {len(rv['ranks'])} entries marked for review, "
          f"{act['note']} noted, {act['confirmed']} confirmed, {len(flags)} flagged** (n = {len(rv['ranks'])} entries)", "",
      f"One row per entry, sorted by vote rank, with the intervals rank-validation reports (its own 90% intervals, not this study's 95% CI) and its own direction, action and flag probability "
      f"(`results/concordance.json`); the data rank is left blank for the {len(blind)} frame-blind entries (glossary). {wide_all} of the {len(rv['ranks'])} data-rank intervals ({wide} of the {len(rv['ranks']) - len(blind)} shown) span ten or more "
      f"places, so these ranks are the other project's finding and set expectations only.", "",
      "| entry | vote rank (90%) | data rank (90%) | rank-validation's direction | action | flag P |", "|---|---|---|---|---|---|"]
for e, rk in sorted(rv["ranks"].items(), key=lambda kv: (kv[1]["vote_rank"], kv[0])):
    dr = "—" if e in blind else f"{rk['lambda_rank']:g} ({rk['lambda_ci'][0]:g}–{rk['lambda_ci'][1]:g})"; fl = flags.get(e)
    flag = f"{fl['probability']:.2f} {fl['direction'].replace('_', ' ')}" if fl else "—"
    L.append(f"| {name(e)} | {rk['vote_rank']:g} ({vci[e][0]:g}–{vci[e][1]:g}) | {dr} | {rk['direction'].replace('lambda', 'data')} | {rk['action']} | {flag} |")

lab = collections.Counter(e for r in JR.values() for e in r["rv_entries"]); gl = collections.Counter(e for r in hand.values() for e in r["gold_labels"])
fn = [int(post["recall"][f"{e}::security"]["beta"] - 1) for e in rv["ranks"]]
L += ["", f"**Table 1.16. How reliable the classifier is for each entry: recall {min(beta_mean(post, 'recall', e)[0] for e in rv['ranks']):.2f}–{max(beta_mean(post, 'recall', e)[0] for e in rv['ranks']):.2f}, "
          f"precision measured on {min(beta_mean(post, 'precision', e)[1] for e in rv['ranks'])} to {max(beta_mean(post, 'precision', e)[1] for e in rv['ranks'])} rows** (n = {len(rv['ranks'])} entries)", "",
      f"Recall (the share of hand-labelled positives the classifier found) and precision (the share of classifier positives the person confirmed) for the `corpus = security` records, each as "
      f"rank-validation's posterior mean, (hits + 1) / (rows + 2) from a Beta(1,1) prior, with the number of hand-labelled rows behind it; the last two columns count the "
      f"hand labels and classifier labels per entry on the {len(JR):,} joined records. False negatives are {min(fn)}–{max(fn)} for every entry, so recall mostly reflects how many classifier-positive rows the entry had.", "",
      "| entry | recall (n) | precision (n) | hand labels on joined rows | classifier labels on joined rows |", "|---|---|---|---|---|"]
for e in sorted(rv["ranks"], key=lambda e: (rv["ranks"][e]["vote_rank"], e)):
    rc, nr = beta_mean(post, "recall", e); pr, npr = beta_mean(post, "precision", e)
    L.append(f"| {name(e)} | {rc:.2f} ({nr}) | {pr:.2f} ({npr}) | {gl[e]:,} | {lab[e]:,} |")

hch = collections.Counter(source_class(C[i]) for i in hand); och = collections.Counter(source_class(C[i]) for i in noent)
rest_h, rest_o = len(hand) - hch["harm-db"], len(noent) - och["harm-db"]
L += ["", f"**Table 1.17. Records the person could place in no entry: {och['harm-db']} of {hch['harm-db']} harm-database rows ({pct(och['harm-db'], hch['harm-db'])}%), "
          f"{rest_o} of {rest_h} elsewhere ({pct(rest_o, rest_h)}%)** (n = {len(hand):,} hand-labelled records)", "",
      "Hand-labelled records that join a current record, by disclosure channel and by step-2 population, with how many of each the person judged to fit none of the 20 entries. "
      "Percentages are within the row; the corpus attack vectors of these records are read in Table 5.5.", "",
      "| group | hand-labelled | no entry fits | % |", "|---|---|---|---|"]
L += [f"| channel: {x} | {hch[x]:,} | {och[x]:,} | {pct(och[x], hch[x])} |" for x in CHANNELS]
if SPLIT:
    hp = collections.Counter(SPLIT[i]["population"] for i in hand); op = collections.Counter(SPLIT[i]["population"] for i in noent)
    L += [f"| population: {p} | {hp[p]:,} | {op[p]:,} | {pct(op[p], hp[p])} |" for p in ("ON-AI", "WITH-AI", "BOTH", "UNRESOLVED", "NONE")]
else: L += [f"| population | — | — | {popc([])} |"]

deep = sum((C[i].get("attack_vector") or "other") == "deepfake" for i in noent)
L += ["", f"**Why the corpus's ranking and the person's labels part ways.** Three channel-specific label monopolies: {NM['corpus']['LLM04']} sits on {sc:,} of its {ol['LLM04']:,} assignments "
          f"in the CVE/GHSA channel ({pct(sc, len(cve))}% of that channel's records), {NM['corpus']['LLM07']} on {mis_ch['harm-db']:,} of its {ol['LLM07']:,} in harm databases, and OWASP coverage is "
          f"{cov['cve/ghsa']}% of cve/ghsa against {cov['harm-db']}% of harm-db records. These are why the corpus rank and the hand labels disagree in step 5 (Tables 5.1–5.2), and the "
          f"{deep} deepfake records among the {len(noent)} no-entry records are the mechanism behind Table 5.5."]
write("s01_overview.md", L)
