#!/usr/bin/env python3
"""s01_overview.py — Step 1. What the data is, general breakdowns, and what the
incident-rank-validation artifacts show. NO dissection into ON-AI / WITH-AI here.

Part A runs the README usage snippet from github.com/emmanuelgjr/genai_incidents verbatim.
Part B profiles the full corpus. Part C reads incident-rank-validation's committed artifacts.
Every table carries a description; where a % column does not sum to 100 the output says why.
Output: out/s01_overview.md
"""
import collections, json, re
from importlib.metadata import version
from genai_incidents import query, by_cve, resolve_id            # README snippet imports
from common import load_full, load_rv, join_rv, beta_mean, source_class, table, sum_note, write, READ, EXT, CYCLE

L = ["# Step 1 — Overview", "",
     f"Inputs: genai-incidents {version('genai-incidents')}, full JSON sha256 {json.load(open(EXT/'PINS.json'))['incidents_json_sha256'][:12]}…. "
     "Generated by `s01_overview.py` (`make s01`); do not edit by hand.", "",
     READ]

# ---------------- A. README snippet, verbatim
hits = list(query(severity="Critical", attack_vector="prompt-injection", year=2026))
L += ["", "## A. README usage snippet (package API)", "",
      "The usage snippet from the package README, run as written, to confirm the pinned package answers as documented. "
      "The first call lists matching records as `id - title` (titles are cut by the corpus, not here); the two lookups follow.", "", "```",
      f'query(severity="Critical", attack_vector="prompt-injection", year=2026) -> {len(hits)} records']
for inc in hits:
    L.append(f'{inc["id"]} - {inc["title"]}')
L.append(f'by_cve("CVE-2026-21520") -> {[i["id"] for i in by_cve("CVE-2026-21520")]}')
L.append(f'resolve_id("INC-00139") -> {resolve_id("INC-00139")}')
L.append("```")

# ---------------- B. general corpus profile (full JSON)
C = load_full(); R = list(C.values()); n = len(R)
S = [s for r in R for s in r["source_ids"]]; early = sum(r["year"] < 2019 for r in R); merged = sum(len(r["source_ids"]) > 1 for r in R)

def multi(field, what):
    """Description tail for a multi-label field: n counts assignments, not records."""
    k = [len(r.get(field) or []) for r in R]; w = sum(x > 0 for x in k)
    return (f"A record can carry several {what} or none: {w:,} of {n:,} records carry at least one and {n-w:,} carry none. "
            f"n therefore counts the {sum(k):,} assignments ({sum(k)/w:.2f} per record that has any), and % is the share of assignments, not of records.")

L += ["", "## B. What the data is", "",
      f"- Records: **{n:,}**; landmark tier: **{sum(r['tier']=='landmark' for r in R):,}**; years {min(r['year'] for r in R)}–{max(r['year'] for r in R)}",
      f"- Records with a CVE: {sum(bool(r.get('cve_ids')) for r in R):,}; with a CWE: {sum(bool(r.get('cwe_ids')) for r in R):,}; merged from >1 source: {merged:,}",
      f"- Median description length: {sorted(len(r.get('description') or '') for r in R)[n//2]} chars"]
L += table("Source", S, lambda s: re.match(r"[A-Za-z]*", s).group(0) or s,
           desc="Which upstream tracker each record was drawn from, read off the alphabetic prefix of each entry in `source_ids`. "
                f"A record merged from several trackers carries several ids ({merged:,} records do), so n counts the {len(S):,} source ids "
                f"across {n:,} records, and % is the share of ids, not of records.")
L += table("Disclosure channel (derived)", R, source_class,
           desc="One channel per record, assigned by `common.source_class`: `cve/ghsa` if the record has a CVE id or a CVE/GHSA source id; "
                "otherwise `harm-db` if it has an OECD, AIID, AIAAIC or AVID source id; otherwise `research/other`. The first match wins, "
                "so a record listed in both a CVE feed and a harm database counts as `cve/ghsa`. Later steps report results within these channels.")
L += table("Category", R, lambda r: r["category"],
           desc="The corpus's `category` field: the kind of record (a vulnerability disclosure, an incident observed in the real world, research, …). One value per record.")
L += table("Tier", R, lambda r: r["tier"],
           desc="The corpus's `tier` field. `landmark` is its curated subset of notable incidents; `feed` is everything else. One value per record.")
L += table("Quality tier", R, lambda r: r["quality_tier"],
           desc="The corpus's `quality_tier` field: how far a record was vetted (`curated`, `reviewed` or `auto`). It is independent of `tier`. One value per record.")
L += table("Corpus", R, lambda r: r.get("corpus"),
           desc="The corpus's `corpus` field, which separates security records from AI-harm records. One value per record.")
L += table("Record year (2019+)", [r for r in R if r["year"] >= 2019], lambda r: r["year"], top=10, by_value=True,
           desc=f"The corpus's `year` field, in chronological order, for records dated 2019 or later. The {early:,} earlier records "
                f"({min(r['year'] for r in R)}–2018) are left out, so n and % refer to 2019+ records, not to the whole corpus. Record year is "
                "ingestion-affected: it reflects when sources were ingested as well as when incidents happened (2026 includes catch-up "
                "ingestion), so do not read this as a trend.")

L += ["", "## B2. General breakdowns", "",
      "> The labels in this section are the corpus's own heuristic assignments (see its DATASHEET). They describe what the",
      "> heuristics matched, not measured prevalence."]
L += table("Attack vector", R, lambda r: r.get("attack_vector") or "other", top=15,
           desc="The corpus's `attack_vector` field, one value per record. `other` is the corpus's own catch-all value; "
                "it is distinct from the pooled last row, which gathers the less frequent named vectors.")
L += table("Severity", R, lambda r: r["severity"], desc="The corpus's `severity` field, one value per record.")
L += table("OWASP LLM Top 10 (2026) codes", [c for r in R for c in (r.get("owasp_llm") or [])], lambda c: c,
           desc="OWASP LLM Top 10 codes the corpus mapped each record to (`owasp_llm`). " + multi("owasp_llm", "codes"))
L += table("OWASP Agentic (ASI) codes", [c for r in R for c in (r.get("owasp_asi") or [])], lambda c: c,
           desc="OWASP Agentic Security Initiative codes the corpus mapped each record to (`owasp_asi`). " + multi("owasp_asi", "codes"))
L += table("CWE ids (top 10)", [c for r in R for c in (r.get("cwe_ids") or [])], lambda c: c, top=10,
           desc="Weakness ids attached to each record (`cwe_ids`), mostly inherited from CVE records. " + multi("cwe_ids", "CWE ids"))

# ---------------- C. incident-rank-validation artifacts
rv = load_rv(); J = join_rv(C, rv); JR = J["rows"]; G = rv["gold"]; unres = set(J["unresolved"])
snap = json.load(open(CYCLE / "results/corpus_b_corroboration.json"))["corpus_a_incident_count"]
blind = sorted(e for e, x in json.load(open(CYCLE / "calibration/diagnostic.json"))["entry_reports"].items() if "frame-blind" in x["reason"])
gold_kept = sum(r["gold_labels"] is not None for r in JR.values()); gold_unres = sum(i in unres for i in G)
oos = [C[i] for i, r in JR.items() if r["gold_labels"] == []]; n_oos = sum(g["labels"] == [] for g in G.values())
L += ["", "## C. What incident-rank-validation shows about this data", "",
      "Read from the committed artifacts of incident-rank-validation's 2026 OWASP LLM cycle; the engine is not run. These numbers are used to "
      "exclude out-of-scope rows, seed samples and set expectations, never for a cross-entry prevalence claim.", "",
      f"- Snapshot: {snap:,} records (May 2026), of which {len(rv['labels']):,} carry a classifier label. {len(rv['labels'])-len(unres):,} of the labelled ids "
      f"still resolve to a current record and {len(unres):,} do not. The corpus has merged duplicates since the snapshot, so the resolving ids land on "
      f"**{len(JR):,}** distinct current records; everything below is counted on those.",
      f"- Label source: stage-1 rules {sum(r['rv_stage']==1 for r in JR.values()):,}, stage-2 LLM {sum(r['rv_stage']==2 for r in JR.values()):,}.",
      f"- Gold set: {len(G):,} hand-adjudicated rows; adjudicator overrode the model on {sum(g['adjudicated']=='override' for g in G.values()):,}; "
      f"out of scope (no entry applies): {n_oos:,}.",
      f"- Gold rows after the join: {gold_kept:,} of {len(G):,} are attached to a current record ({gold_unres} sit on ids that no longer resolve, "
      f"{len(G)-gold_unres-gold_kept} lose their label where merged duplicates collapse onto one record), including {len(oos):,} of the {n_oos:,} out-of-scope rows.",
      f"- Headline: weighted κ vote-vs-data = {rv['concordance'].get('weighted_kappa_median', 0):.3f}; frame-blind entries: {', '.join(blind)}."]
lab = collections.Counter(e for r in JR.values() for e in r["rv_entries"]); gold = collections.Counter(e for r in JR.values() for e in (r["gold_labels"] or []))
L += ["", "**Vote rank vs data rank vs share of labels, per entry** (sorted by vote rank)", "",
      "One row per taxonomy entry: the ten OWASP LLM entries plus the cycle's NEW- and ROLL- candidates. *Vote rank* is the entry's position in the "
      "community vote (ties and half-ranks come from the source report). *Data rank* is the engine's rank by recall- and precision-corrected incident "
      f"count, with its 90% interval. *% of classifier labels* is the entry's share of the {sum(lab.values()):,} classifier labels on joined records. "
      f"*% of gold labels* is its share of the {sum(gold.values()):,} gold labels on joined gold rows; out-of-scope rows carry no label and are not "
      "in that denominator. *Recall* and *Precision* are posterior means for the security stratum and *n gold* is the number of gold observations "
      "behind the recall estimate; these three are per-entry quantities, not shares, and are not meant to sum to anything.", "",
      "| Entry | Name | Vote rank | Data rank (90% CI) | % of classifier labels | % of gold labels | Recall | Precision | n gold |", "|---|---|---|---|---|---|---|---|---|"]
for e, t in sorted(rv["taxonomy"].items(), key=lambda kv: rv["ranks"].get(kv[0], {}).get("vote_rank", 99)):
    rk = rv["ranks"].get(e, {}); lo, hi = rk.get("lambda_ci", (0, 0))
    rc, nr = beta_mean(rv["posteriors"], "recall", e); pr, _ = beta_mean(rv["posteriors"], "precision", e)
    L.append(f"| {e} | {t['canonical_name']} | {rk.get('vote_rank','?'):g} | {rk.get('lambda_rank','?'):g} ({lo:g}–{hi:g}) | {100*lab[e]/sum(lab.values()):.1f} | {100*gold[e]/sum(gold.values()):.1f} | {rc:.2f} | {pr:.2f} | {nr} |")
notes = [s for s in (sum_note([100*lab[e]/sum(lab.values()) for e in rv["taxonomy"]], 'The "% of classifier labels" column'),
                     sum_note([100*gold[e]/sum(gold.values()) for e in rv["taxonomy"]], 'The "% of gold labels" column')) if s]
if notes: L += ["", " ".join(notes)]
L += table("Disclosure channel of out-of-scope gold rows", oos, source_class,
           desc=f"Where the gold-set out-of-scope rows come from: the {len(oos):,} out-of-scope rows attached to a current record, by the disclosure channel defined in section B.")
L += table("Attack vector of out-of-scope gold rows", oos, lambda r: r.get("attack_vector") or "other", top=6,
           desc="The same rows by the corpus's `attack_vector` field; `other` is the corpus's catch-all value, as in section B2.")
write("s01_overview.md", L)
