#!/usr/bin/env python3
"""s05_techniques.py — Step 5. Draft tables for two questions, following the design of Hamer et al.,
"Closing the Chain" (arXiv:2503.12192): what attackers did -> mitigations that address it -> gaps.

  RQ1  What is most common in ON-AI and in WITH-AI, and what do the records behind it look like?
       Two tables per population. Rows are OWASP categories: the corpus's ATLAS labels are mostly computed from
       them, so the categories are the honest label layer. The same table carries a person's labels and ranking.
  RQ2  Which MITRE ATLAS mitigations address ON-AI attacks, and which common techniques have none?
       Chain: OWASP category -> corpus lookup -> ATLAS technique -> ATLAS mitigation (the paper's "transitive" strategy).

Every label here is a heuristic corpus label, so this is a pre-coding draft: llm(), asi() and techs() are the
places to swap in hand codes once the manual phase has produced them. The technique -> mitigation mapping is
MITRE's own (ATLAS release pinned in external/PINS.json); nothing is mapped by a model.
Output: out/s05_techniques.md
"""
import ast, collections, json
from common import load_full, load_atlas, load_rv, join_rv, source_class, boot_ci, write, OUT, EXT

S = json.load(open(OUT / "split.json")); C = load_full(); A = load_atlas(); REF = json.load(open(EXT / "mitre_atlas.json"))
NAME = {k: v["name"] for f in ("owasp_llm_top10_2026.json", "owasp_asi_top10.json") for k, v in json.load(open(EXT / f))["entries"].items()}
POPS, CH = ("ON-AI", "WITH-AI"), ("cve/ghsa", "harm-db", "research/other")
P = {p: [C[i] for i, s in S.items() if s["population"] == p] for p in POPS}
DEMO = ("research", "research-demonstrated", "red-team")

def llm(r): return r.get("owasp_llm") or []              # <- hand codes replace these three after the manual phase
def asi(r): return r.get("owasp_asi") or []
def techs(r): return r.get("mitre_atlas") or []
def code(c): return f"{c} {NAME[c]}"
def parent(t): return t.rsplit(".", 1)[0] if t.count(".") == 2 else t
def label(t): return f"{t} {(A['techniques'].get(t) or REF['techniques'].get(t) or {}).get('name', '?')}"
def tactics(t): return ", ".join(REF["tactics"][x]["name"] for x in (REF["techniques"].get(t) or {}).get("tactics") or (REF["techniques"].get(parent(t)) or {}).get("tactics") or []) or "—"
def mits(t): return A["mitigates"].get(t, set()) | A["mitigates"].get(parent(t), set())    # a sub-technique inherits its parent's mitigations
def pc(a, b, d=1): return f"{100*a/b:.{d}f}" if b else "—"
def npc(a, b): return f"{a:,} ({pc(a, b)}%)"
def ranks(counter): return {k: 1 + sum(w > v for w in counter.values()) for k, v in counter.items() if v}    # ties share a rank
def lead(counter, n): return " / ".join(f"{k} {100*v/n:.0f}%" for k, v in counter.most_common(1)) or "—"

def crosswalk():
    """OWASP code -> ATLAS technique back-fill tables, read (never run) from the corpus's build script at the pinned tag."""
    out = {}
    for node in ast.parse((EXT / "corpus_merge_and_dedupe.py").read_text()).body:
        if isinstance(node, ast.Assign) and getattr(node.targets[0], "id", "") in ("LLM_TO_ATLAS", "ASI_TO_ATLAS"): out.update(ast.literal_eval(node.value))
    return out
XW = crosswalk()
# Crosswalk links this study judges wrong (a judgement, not a measurement; edit here). RQ2 drops the techniques they produce.
SUSPECT = {"LLM07": "misinformation is not model poisoning"}
def backfill(r, skip=()): return {t for c in llm(r) + asi(r) if c not in skip for t in XW.get(c, [])}
def sound(r): return set(techs(r)) - (backfill(r) - backfill(r, SUSPECT))      # technique labels minus those that only a suspect link produces
def via(t): return ", ".join(c for c in sorted(XW) if t in XW[c]) or "—"

# rank-validation gold labels use their own numbering for the same ten OWASP entries: match by name, never by number
rv = load_rv(); J = join_rv(C, rv)["rows"]
norm = lambda s: s.lower().replace("vulnerabilities", "").replace("weaknesses", "").replace(" and ", " ").strip()
RV2C = {e: next(k for k in NAME if k.startswith("LLM") and norm(NAME[k]) == norm(t["canonical_name"])) for e, t in rv["taxonomy"].items() if e.startswith("LLM")}
GOLD = {p: [(C[i], J[i]["gold_labels"]) for i, s in S.items() if s["population"] == p and i in J and J[i]["gold_labels"] is not None] for p in POPS}

L = ["# Step 5 — What attackers did, and the mitigations that address it (draft, pre-coding)", "",
     "Generated by `s05_techniques.py` (`make s05`); do not edit by hand. The design follows Hamer et al., *Closing the Chain* (arXiv:2503.12192): "
     "collect what attackers did, map it to the framework tasks that mitigate it, rank the tasks, and list what the framework leaves uncovered. "
     "Three things differ from that paper and limit what these tables can claim:", "",
     "- **Labels are not coded from reports.** The corpus assigns OWASP categories by keyword rules, then computes most ATLAS techniques from them "
     "with a fixed lookup. RQ1 therefore reports OWASP categories, the layer the rest is derived from, next to a human check of the same records.",
     "- **OWASP categories are kinds of risk, not techniques.** They say what kind of weakness or harm a record was filed under, not how the attacker "
     "operated. Technique-level claims wait for the hand-coding phase.",
     f"- **One mapping chain, not four independent strategies.** RQ2 runs OWASP category → corpus lookup → ATLAS technique → ATLAS mitigation, using "
     f"MITRE's own `mitigates` relationships in ATLAS {json.load(open(EXT / 'PINS.json'))['atlas_release']}. There is no LLM or report-derived mapping to triangulate against.", "",
     "How to read the tables: a record can carry several categories or techniques, so their percentages are shares of records carrying the label and "
     "do not sum to 100. Percentages are rounded to one decimal unless a column says otherwise. ON-AI and WITH-AI are separate populations and are "
     "never pooled; 95% CIs are percentile bootstrap intervals over records (2,000 resamples). Category numbers (LLM01 …) are the corpus's; the "
     "project that supplied the human labels numbers the same ten categories differently, so the two are matched here by name."]

# ---------------- RQ1: two tables per population
L += ["", "## RQ1. What is most common, and what do the records behind it look like?"]
for p in POPS:
    rows, n = P[p], len(P[p]); chan = {c: [r for r in rows if source_class(r) == c] for c in CH}
    cnt = collections.Counter(c for r in rows for c in set(llm(r))); k = [len(set(llm(r))) for r in rows if llm(r)]
    # the person's labels for the same population: one row per category chosen, plus "none fits"
    G = GOLD[p]; hum = collections.Counter(RV2C.get(e, e) for _, gl in G for e in gl); none = sum(gl == [] for _, gl in G)
    crank, hrank = ranks(cnt), ranks(hum)
    L += ["", f"**{p}: OWASP LLM Top 10 categories, corpus labels beside human labels** (n = {n:,} records; {len(G)} of them also labelled by a person)", "",
          f"Every OWASP LLM Top 10 (2026) category the corpus assigns to {p} records, most frequent first, with the corpus's ranking. *Corpus-labelled "
          f"records* is how many carry the category and their share of the population; {n - len(k):,} records carry none and the rest carry "
          f"{sum(k)/len(k):.1f} on average, so those shares do not sum to 100. The three channel columns give the share of that channel's {p} records "
          "carrying the category (" + ", ".join(f"{c} n = {len(chan[c]):,}" for c in CH) + "), because each disclosure channel observes a different population. "
          f"The last two columns show what a person decided for the same population. A separate project (incident-rank-validation) had a person label "
          f"a sample of records by hand, and {len(G)} of those are {p} records. *Human-labelled records* is how many of them the person filed under the "
          "category, and *human rank* ranks the categories by that count. The person could also choose from ten proposed additions to the Top 10, or "
          "decide that no category fits; those appear as extra rows at the bottom, with dashes in the corpus columns because the corpus has no such "
          "label. The human shares sum to 100 up to rounding and the few records given two labels. The sample was drawn a fixed number per category "
          "to calibrate a classifier, not at random from the corpus, so the human share and rank describe that sample: use them to see where the two "
          "labellings part ways, not as prevalence.", "",
          "| category | corpus-labelled records | corpus rank | 95% CI | % in cve/ghsa | % in harm-db | % in research/other | human-labelled records | human rank |", "|---|---|---|---|---|---|---|---|---|"]
    for c, v in cnt.most_common():
        _, lo, hi = boot_ci(rows, lambda r, c=c: c in llm(r))
        L.append(f"| {code(c)} | {npc(v, n)} | {crank[c]} | {100*lo:.1f}–{100*hi:.1f} | " + " | ".join(pc(sum(c in llm(r) for r in chan[x]), len(chan[x])) for x in CH)
                 + f" | {npc(hum[c], len(G))} | {hrank.get(c, '—')} |")
    for e, v in hum.most_common():
        if e not in NAME: L.append(f"| {rv['taxonomy'][e]['canonical_name']} *(proposed addition)* | — | — | — | — | — | — | {npc(v, len(G))} | {hrank[e]} |")
    L.append(f"| *No category fits* | — | — | — | — | — | — | {npc(none, len(G))} | — |")
    L += ["", f"**{p}: what the records behind each category look like**", "",
          "The same categories, profiled by corpus fields. This is the data's answer to *why* a category ranks where it does: which kind of record "
          "carries it. Each cell is a share of the category's own records, rounded to a whole percent. *Top attack vector* and *top CWE* show only the "
          "single most frequent value, so they do not sum to 100. *CVE or CWE* is the share with a CVE or CWE id. *Demonstrated* is the share whose "
          "`category` field is research, research-demonstrated or red-team, as opposed to realized or disclosed. *Most often paired with* is the other "
          "OWASP category most often on the same record.", "",
          "| category | records | top attack vector | CVE or CWE (%) | top CWE | demonstrated (%) | most often paired with |", "|---|---|---|---|---|---|---|"]
    for c, m in cnt.most_common():
        h = [r for r in rows if c in llm(r)]
        L.append(f"| {code(c)} | {m:,} | {lead(collections.Counter(r.get('attack_vector') or 'other' for r in h), m)} | {pc(sum(bool(r.get('cve_ids') or r.get('cwe_ids')) for r in h), m, 0)} | "
                 f"{lead(collections.Counter(x for r in h for x in set(r.get('cwe_ids') or [])), m)} | {pc(sum(r['category'] in DEMO for r in h), m, 0)} | "
                 f"{lead(collections.Counter(code(u) for r in h for u in set(llm(r)) if u != c), m)} |")

# ---------------- RQ2
ON, n_on = P["ON-AI"], len(P["ON-AI"]); M = A["mitigations"]
derived = {p: pc(sum(len(set(techs(r)) & backfill(r)) for r in P[p]), sum(len(set(techs(r))) for r in P[p])) for p in POPS}
CNT = {p: collections.Counter(t for r in P[p] for t in sound(r)) for p in POPS}
L += ["", "## RQ2. Which mitigations address ON-AI attacks, and what is left uncovered?", "",
      "**The chain from OWASP category to ATLAS mitigation**", "",
      "ATLAS is the only framework here that publishes a machine-readable link from what attackers do to what mitigates it, so RQ2 has to go through "
      "ATLAS techniques. The corpus gets those techniques from its OWASP categories with the lookup below, for both the LLM Top 10 and the Agentic "
      f"(ASI) list: {derived['ON-AI']}% of all ATLAS technique labels on ON-AI records, and {derived['WITH-AI']}% on WITH-AI records, are what this lookup "
      "produces from the record's own OWASP categories. Each row is one link, with both names so it can be judged, and the number of mitigations "
      "ATLAS lists for the technique. *Judged unsound* marks links this study rejects; that is a judgement recorded in the script, not a "
      "measurement, and the techniques such a link produces are left out of everything below. *ON-AI records* is the number of ON-AI records "
      "carrying the category.", "",
      "| OWASP category | ATLAS technique it becomes | judged unsound | ATLAS mitigations (n) | ON-AI records with the category |", "|---|---|---|---|---|"]
for c in sorted(XW, key=lambda c: (c[:3] != "LLM", c)):
    for t in XW[c]:
        L.append(f"| {code(c)} | {label(t)} | {SUSPECT.get(c, '')} | {len(mits(t))} | {npc(sum(c in llm(r) + asi(r) for r in ON), n_on)} |")

g = GOLD["WITH-AI"]; g_oos = sum(gl == [] for _, gl in g); g_cand = sum(bool(gl) and not any(e in RV2C for e in gl) for _, gl in g)
L += ["", "**How much of each population ATLAS mitigations reach**", "",
      "The counterpart of the paper's framework measures, after dropping techniques produced only by a link judged unsound. *Techniques with a "
      "mitigation* counts each distinct technique once; *technique labels with a mitigation* counts every (record, technique) label, so frequent "
      "techniques weigh more. *Mitigations in use* is the paper's coverage: ATLAS mitigations that address at least one technique observed in the "
      "population, out of all ATLAS mitigations.", "",
      "| measure | " + " | ".join(POPS) + " |", "|---|---|---|"]
def measure(name, f): L.append(f"| {name} | " + " | ".join(f(p) for p in POPS) + " |")
measure("records", lambda p: f"{len(P[p]):,}")
measure("records with at least one technique label", lambda p: npc(sum(bool(sound(r)) for r in P[p]), len(P[p])))
measure("records with at least one mitigated technique", lambda p: npc(sum(any(mits(t) for t in sound(r)) for r in P[p]), len(P[p])))
measure("distinct techniques observed", lambda p: f"{len(CNT[p])}")
measure("techniques with a mitigation", lambda p: npc(sum(bool(mits(t)) for t in CNT[p]), len(CNT[p])))
measure("technique labels with a mitigation", lambda p: npc(sum(v for t, v in CNT[p].items() if mits(t)), sum(CNT[p].values())))
measure("mitigations in use (coverage)", lambda p: npc(sum(any(m in mits(t) for t in CNT[p]) for m in M), len(M)))
L += ["", f"The rest of RQ2 is ON-AI only. Both frameworks are written for whoever defends an AI system, and in WITH-AI the AI is the attacker's tool: of "
          f"the {len(g)} WITH-AI records a person labelled by hand, {npc(g_oos, len(g))} were judged to fit no OWASP category and {npc(g_cand, len(g))} were "
          f"filed under proposed additions outside the Top 10. The measures above show the same thing from the ATLAS side."]

cov = {m: sum(any(m in mits(t) for t in sound(r)) for r in ON) for m in M}
hit = {m: sorted(t for t in CNT["ON-AI"] if m in mits(t)) for m in M}
ranked = sorted((m for m in M if cov[m]), key=lambda m: (-cov[m], -len(hit[m]), m))
L += ["", f"**ON-AI: ATLAS mitigations ranked by the records they address** ({len(ranked)} of {len(M)} ATLAS mitigations address at least one ON-AI record)", "",
      "The counterpart of the paper's starter kit. A mitigation *addresses* a technique if ATLAS lists a `mitigates` relationship to it or to its "
      "parent technique. *Records addressed* is the share of ON-AI records carrying at least one technique the mitigation addresses; a record can be "
      "addressed by several mitigations, so the column does not sum to 100. The paper ranks by attacks mitigated × techniques mitigated; with one "
      "population there is no attack count to multiply by, so rows are ranked by records addressed and the technique count is shown beside it. "
      "*OWASP categories reached* lists the categories whose technique in the chain above the mitigation addresses, which is how the ranking ties "
      "back to RQ1. "
      "*Category* and *lifecycle phases* are ATLAS's own fields and say who would have to implement the mitigation and when.", "",
      "| mitigation | category | lifecycle phases | records addressed | techniques addressed (n) | OWASP categories reached |", "|---|---|---|---|---|---|"]
for m in ranked:
    reach = sorted({c for c in XW if c not in SUSPECT and any(t in hit[m] for t in XW[c])}, key=lambda c: (c[:3] != "LLM", c))
    L.append(f"| {m} {M[m]['name']} | {', '.join(M[m]['categories'])} | {', '.join(M[m]['lifecycle'])} | {npc(cov[m], n_on)} | {len(hit[m])} | {', '.join(reach) or '—'} |")

gaps = sorted((t for t in CNT["ON-AI"] if not mits(t)), key=lambda t: -CNT["ON-AI"][t])
L += ["", f"**ON-AI: common techniques with no ATLAS mitigation** (top {min(10, len(gaps))} of {len(gaps)})", "",
      "The counterpart of the paper's gap analysis: techniques labelled on ON-AI records for which ATLAS lists no mitigation, most frequent first. "
      "*ATT&CK technique* is the Enterprise ATT&CK technique ATLAS says the entry is adapted from; where one is given, mitigations exist in ATT&CK "
      "but are not carried into ATLAS, so the gap is in the framework's coverage and not in security knowledge. Where none is given, no framework "
      "mapped in this study offers a mitigation.", "",
      "| technique | tactic | ON-AI records | OWASP categories that lead to it | ATT&CK technique |", "|---|---|---|---|---|"]
for t in gaps[:10]:
    L.append(f"| {label(t)} | {tactics(t)} | {npc(CNT['ON-AI'][t], n_on)} | {via(t)} | {(A['techniques'].get(t) or A['techniques'].get(parent(t)) or {}).get('attack_ref') or '—'} |")

L += ["", "## What these tables cannot say", "",
      "- **Whether a mitigation is implemented.** Nothing in the corpus records which controls a victim had in place. The category and lifecycle "
      "columns describe who would have to act and when; adoption needs evidence from outside the corpus.",
      "- **How attackers operated.** OWASP categories are kinds of risk and the ATLAS labels are mostly computed from them. Prevalence follows the "
      "corpus's rules and its disclosure channels; the channel and human-check columns are there so each row can be discounted accordingly.",
      "- **Chains.** A record's labels are an unordered set, so nothing here orders them into an attack sequence."]
write("s05_techniques.md", L)
