#!/usr/bin/env python3
"""s05_techniques.py — Step 5. Draft tables for two questions, following the design of Hamer et al.,
"Closing the Chain" (arXiv:2503.12192): techniques used -> mitigations that address them -> gaps.

  RQ1  Which attack techniques are most common in ON-AI and in WITH-AI, and what do the records behind them look like?
  RQ2  Which MITRE ATLAS mitigations address those techniques, and which common techniques have none?

Technique labels are the corpus's heuristic `mitre_atlas` field, so this is a pre-coding draft: techs() is the
one place to swap in hand-coded techniques once the manual phase has produced them. The technique -> mitigation
mapping is MITRE's own (ATLAS release pinned in external/PINS.json); nothing here is mapped by hand or by a model.
Output: out/s05_techniques.md
"""
import ast, collections, json
from common import load_full, load_atlas, source_class, boot_ci, write, OUT, EXT

S = json.load(open(OUT / "split.json")); C = load_full(); A = load_atlas(); REF = json.load(open(EXT / "mitre_atlas.json"))
POPS, CH, TOP = ("ON-AI", "WITH-AI"), ("cve/ghsa", "harm-db", "research/other"), 12
P = {p: [C[i] for i, s in S.items() if s["population"] == p] for p in POPS}

def techs(r): return r.get("mitre_atlas") or []          # <- replace with hand-coded techniques after the manual phase
def parent(t): return t.rsplit(".", 1)[0] if t.count(".") == 2 else t
def label(t): return f"{t} {(A['techniques'].get(t) or REF['techniques'].get(t) or {}).get('name', '?')}"
def tactics(t): return ", ".join(REF["tactics"][x]["name"] for x in (REF["techniques"].get(t) or {}).get("tactics") or (REF["techniques"].get(parent(t)) or {}).get("tactics") or []) or "—"
def mits(t): return A["mitigates"].get(t, set()) | A["mitigates"].get(parent(t), set())    # a sub-technique inherits its parent's mitigations
def pc(a, b, d=1): return f"{100*a/b:.{d}f}" if b else "—"
def lead(counter, n): return " / ".join(f"{k} {100*v/n:.0f}%" for k, v in counter.most_common(1)) or "—"

def crosswalk():
    """OWASP code -> ATLAS technique back-fill tables, read (never run) from the corpus's build script at the pinned tag."""
    out = {}
    for node in ast.parse((EXT / "corpus_merge_and_dedupe.py").read_text()).body:
        if isinstance(node, ast.Assign) and getattr(node.targets[0], "id", "") in ("LLM_TO_ATLAS", "ASI_TO_ATLAS"): out.update(ast.literal_eval(node.value))
    return out
XW = crosswalk()
def backfill(r): return {t for c in (r.get("owasp_llm") or []) + (r.get("owasp_asi") or []) for t in XW.get(c, [])}

CNT = {p: collections.Counter(t for r in P[p] for t in set(techs(r))) for p in POPS}
L = ["# Step 5 — Attack techniques and the mitigations that address them (draft, pre-coding)", "",
     "Generated by `s05_techniques.py` (`make s05`); do not edit by hand. The design follows Hamer et al., *Closing the Chain* (arXiv:2503.12192): "
     "collect the techniques attackers used, map each technique to the framework tasks that mitigate it, rank the tasks, and list what the "
     "framework leaves uncovered. Two things differ from that paper and limit what these tables can claim:", "",
     "- **Technique labels are not coded from reports.** They are the corpus's `mitre_atlas` field, which its build script fills by keyword rules "
     "and by a fixed OWASP-code → ATLAS-technique crosswalk. The tables say what those rules matched. The *reproducible from OWASP codes* column "
     "shows, per technique, how much of the count the crosswalk alone would produce.",
     f"- **One mapping strategy, not four.** Technique → mitigation links are MITRE's own `mitigates` relationships in ATLAS {json.load(open(EXT / 'PINS.json'))['atlas_release']} "
     "(the paper's \"framework\" strategy). There is no transitive, LLM or report-derived mapping to triangulate against.", "",
     "How to read the tables: a record can carry several techniques, so technique percentages are shares of records that carry the technique and "
     "do not sum to 100. Percentages are rounded to one decimal unless a column says otherwise. ON-AI and WITH-AI are separate populations and are "
     "never pooled; 95% CIs are percentile bootstrap intervals over records (2,000 resamples)."]

# ---------------- RQ1
L += ["", "## RQ1. Which techniques are most common, and what do the records behind them look like?"]
for p in POPS:
    rows, n, cnt = P[p], len(P[p]), CNT[p]; chan = {c: [r for r in rows if source_class(r) == c] for c in CH}
    top = [t for t, _ in cnt.most_common(TOP)]; has = {t: [r for r in rows if t in techs(r)] for t in top}
    none, k = sum(not techs(r) for r in rows), [len(set(techs(r))) for r in rows if techs(r)]
    L += ["", f"**{p}: technique prevalence** (n = {n:,} records)", "",
          f"The {TOP} most frequent of the {len(cnt)} ATLAS techniques labelled on {p} records. {none:,} records carry no technique and the rest carry "
          f"{sum(k)/len(k):.1f} on average, which is why the % column sums to more than 100. *Tactic* and *ATLAS maturity* come from ATLAS, not from the "
          "records (maturity is ATLAS's own rating of whether the technique is feasible, demonstrated or realized in the wild). The three channel columns "
          f"give the share of that channel's {p} records carrying the technique (" + ", ".join(f"{c} n = {len(chan[c]):,}" for c in CH) + "), because each "
          "disclosure channel observes a different population. *Reproducible from OWASP codes* is the share of the technique's records where the corpus's "
          "crosswalk would assign it from the record's OWASP codes; near 100 means the row restates an OWASP code and is not independent technique "
          "evidence. *Curated* counts the technique's records in the corpus's hand-curated quality tier.", "",
          "| technique | tactic | ATLAS maturity | n | % of records | 95% CI | % in cve/ghsa | % in harm-db | % in research/other | reproducible from OWASP codes (%) | curated (n) |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    xw = {t: sum(t in backfill(r) for r in has[t]) / len(has[t]) for t in top}
    for t in top:
        _, lo, hi = boot_ci(rows, lambda r, t=t: t in techs(r))
        L.append(f"| {label(t)} | {tactics(t)} | {(A['techniques'].get(t) or {}).get('maturity') or '—'} | {len(has[t]):,} | {pc(len(has[t]), n)} | {100*lo:.1f}–{100*hi:.1f} | "
                 + " | ".join(pc(sum(t in techs(r) for r in chan[c]), len(chan[c])) for c in CH)
                 + f" | {100*xw[t]:.1f} | {sum(r['quality_tier'] == 'curated' for r in has[t])} |")
    L += ["", f"*{sum(v >= 0.9 for v in xw.values())} of these {len(top)} rows are at least 90% reproducible from the record's OWASP codes: for those rows the technique "
              "count is the OWASP-code count under another name.*"]
    L += ["", f"**{p}: what the records behind each technique look like**", "",
          "The same techniques, profiled by corpus fields. This is the data's answer to *why* a technique ranks where it does: which kind of record "
          "carries the label. Each cell is a share of the technique's own records, rounded to a whole percent. *Top attack vector* and *top CWE* show only "
          "the single most frequent value, so they do not sum to 100. *CVE or CWE* is the share with a CVE or CWE id. *Demonstrated* is the share whose "
          "`category` is research, research-demonstrated or red-team, as opposed to realized or disclosed. *Most co-labelled technique* is the other "
          "technique most often on the same record.", "",
          "| technique | n | top attack vector | CVE or CWE (%) | top CWE | demonstrated (%) | most co-labelled technique |", "|---|---|---|---|---|---|---|"]
    for t in top:
        h = has[t]; m = len(h)
        L.append(f"| {label(t)} | {m:,} | {lead(collections.Counter(r.get('attack_vector') or 'other' for r in h), m)} | {pc(sum(bool(r.get('cve_ids') or r.get('cwe_ids')) for r in h), m, 0)} | "
                 f"{lead(collections.Counter(c for r in h for c in set(r.get('cwe_ids') or [])), m)} | {pc(sum(r['category'] in ('research', 'research-demonstrated', 'red-team') for r in h), m, 0)} | "
                 f"{lead(collections.Counter(label(u) for r in h for u in set(techs(r)) if u != t), m)} |")

# ---------------- RQ2
OBS = set(CNT["ON-AI"]) | set(CNT["WITH-AI"]); M = A["mitigations"]
cov = {m: {p: sum(any(m in mits(t) for t in techs(r)) for r in P[p]) for p in POPS} for m in M}
hit = {m: sorted(t for t in OBS if m in mits(t)) for m in M}
score = {m: sum(cov[m][p] > 0 for p in POPS) * len(hit[m]) for m in M}
ranked = sorted((m for m in M if score[m]), key=lambda m: (-score[m], -sum(cov[m].values()), m))
L += ["", "## RQ2. Which mitigations address these techniques, and what is left uncovered?", "",
      f"**ATLAS mitigations ranked by the techniques they address** ({len(ranked)} of {len(M)} ATLAS mitigations address at least one observed technique)", "",
      "The counterpart of the paper's starter kit. A mitigation *addresses* a labelled technique if ATLAS lists a `mitigates` relationship to that "
      "technique or to its parent technique. *Score* is the paper's formula with populations in place of attacks: the number of populations in which "
      "the mitigation addresses at least one record (0–2) times the number of observed techniques it addresses. *Records addressed* is the share of each "
      "population's records carrying at least one technique the mitigation addresses; a record can be addressed by several mitigations, so these "
      "columns do not sum to 100. Reach inherits the labelling: a mitigation that addresses a crosswalk-assigned technique is credited with every record "
      "carrying the corresponding OWASP code. *Category* and *lifecycle phases* are ATLAS's own fields and say who would have to implement the mitigation and "
      f"when. Rows are sorted by score; the {len(M) - len(ranked)} mitigations that address no observed technique are not shown.", "",
      "| mitigation | category | lifecycle phases | observed techniques addressed (n) | ON-AI records addressed (%) | WITH-AI records addressed (%) | score |", "|---|---|---|---|---|---|---|"]
for m in ranked:
    L.append(f"| {m} {M[m]['name']} | {', '.join(M[m]['categories'])} | {', '.join(M[m]['lifecycle'])} | {len(hit[m])} | "
             + " | ".join(f"{cov[m][p]:,} ({pc(cov[m][p], len(P[p]))})" for p in POPS) + f" | {score[m]} |")

L += ["", "**How much of each population ATLAS mitigations reach**", "",
      "The counterpart of the paper's framework measures, for the one framework with a machine-readable technique → mitigation mapping. *Techniques "
      "with a mitigation* and *technique labels with a mitigation* differ because techniques are not equally frequent: the first counts each "
      "distinct technique once, the second counts every (record, technique) label. *Mitigations in use* is the paper's coverage: ATLAS mitigations "
      "that address at least one technique observed in the population, out of all ATLAS mitigations.", "",
      "| measure | " + " | ".join(POPS) + " |", "|---|---|---|"]
def measure(name, f): L.append(f"| {name} | " + " | ".join(f(p) for p in POPS) + " |")
measure("records", lambda p: f"{len(P[p]):,}")
measure("records with at least one technique label", lambda p: (lambda a: f"{a:,} ({pc(a, len(P[p]))}%)")(sum(bool(techs(r)) for r in P[p])))
measure("records with at least one mitigated technique", lambda p: (lambda a: f"{a:,} ({pc(a, len(P[p]))}%)")(sum(any(mits(t) for t in techs(r)) for r in P[p])))
measure("distinct techniques observed", lambda p: f"{len(CNT[p])}")
measure("techniques with a mitigation", lambda p: (lambda a: f"{a} ({pc(a, len(CNT[p]))}%)")(sum(bool(mits(t)) for t in CNT[p])))
measure("technique labels with a mitigation", lambda p: (lambda a, b: f"{a:,} of {b:,} ({pc(a, b)}%)")(sum(v for t, v in CNT[p].items() if mits(t)), sum(CNT[p].values())))
measure("mitigations in use (coverage)", lambda p: (lambda a: f"{a} of {len(M)} ({pc(a, len(M))}%)")(sum(cov[m][p] > 0 for m in M)))

gaps = sorted((t for t in OBS if not mits(t)), key=lambda t: -(CNT["ON-AI"][t] + CNT["WITH-AI"][t]))
L += ["", f"**Common techniques with no ATLAS mitigation** (top {min(10, len(gaps))} of {len(gaps)})", "",
      "The counterpart of the paper's gap analysis: observed techniques for which ATLAS lists no mitigation, most frequent first. Counts are records "
      "carrying the technique, with the share of the population. *ATT&CK technique* is the Enterprise ATT&CK technique ATLAS says the entry is adapted "
      "from; where one is given, mitigations exist in ATT&CK but are not carried into ATLAS, so the gap is in the framework's coverage and not in "
      "security knowledge. Where none is given, no mapped framework in this study offers a mitigation.", "",
      "| technique | tactic | ON-AI records | WITH-AI records | ATT&CK technique |", "|---|---|---|---|---|"]
for t in gaps[:10]:
    L.append(f"| {label(t)} | {tactics(t)} | " + " | ".join(f"{CNT[p][t]:,} ({pc(CNT[p][t], len(P[p]))}%)" for p in POPS) + f" | {(A['techniques'].get(t) or A['techniques'].get(parent(t)) or {}).get('attack_ref') or '—'} |")

L += ["", "## What these tables cannot say", "",
      "- **Whether a mitigation is implemented.** Nothing in the corpus records which controls a victim had in place. The category and lifecycle "
      "columns describe who would have to act and when; adoption needs evidence from outside the corpus.",
      "- **Technique prevalence in the world.** Counts follow the corpus's labelling rules and its disclosure channels. The channel columns and the "
      "*reproducible from OWASP codes* column are there so each row can be discounted accordingly.",
      "- **Chains.** A record's techniques are an unordered set, so nothing here orders them into an attack sequence."]
write("s05_techniques.md", L)
