#!/usr/bin/env python3
"""s06_compare.py — Step 6. The only step that looks at the labels before review: pre (the first value, from a keyword rule or the corpus label), current (the reviewed
value) and current for 2026 records, one table per population, with worked examples of labels that changed and why.

Pre = step 4's value from its keyword rules or the corpus attack-vector label, 'unstated' otherwise (out/dataset_pre.csv).
Current = the reviewed value (out/dataset_post.csv). 2026 = the current value for records whose corpus year is 2026.
Reads out/dataset_pre.csv, out/dataset_post.csv, out/methodology.json (the words each keyword rule matched), coded/review.json and
coded/relabels.json (reviewer and coder notes). No model calls; the worked examples are a fixed list of record ids, checked against the
data when the script runs, and every sentence about them is assembled from the files above.
Output: out/s06_compare.md
"""
import collections, csv, json
from common import write, READ, OUT, ROOT

PRE = {r["id"]: r for r in csv.DictReader(open(OUT / "dataset_pre.csv", encoding="utf-8"))}
POST = {r["id"]: r for r in csv.DictReader(open(OUT / "dataset_post.csv", encoding="utf-8"))}
METH = json.load(open(OUT / "methodology.json"))
REV = json.load(open(ROOT / "coded" / "review.json")); CODED = json.load(open(ROOT / "coded" / "relabels.json"))["labels"]
RNOTE = {(c["id"], c["dim"]): c for c in REV["corrections"]}
DIMS = {"ON-AI": ("entry_point", "target"), "WITH-AI": ("ai_role", "objective")}
NAME = {"entry_point": "Entry point", "target": "Target", "ai_role": "AI medium", "objective": "Objective"}
YEAR = "2026"
assert set(PRE) == set(POST), "pre and post datasets hold different records"

# one row per label: (dim, id, pre, current, how, year)
LAB = [(d, i, r[d + "_pre"], r[d + "_post"], r[d + "_how"], r["year"]) for i, r in POST.items() for d in (*DIMS["ON-AI"], *DIMS["WITH-AI"]) if r[d + "_post"]]
for d, i, pre, cur, how, _ in LAB:
    assert pre == PRE[i][d], (i, d)                                                       # the post file's pre column is the pre file's value
    assert pre == "unstated" or pre == cur or how == "corrected by review", (i, d, how)   # only the review replaces a first value
changed = lambda x: x[2] != x[3]
pc = lambda a, b: f"{100 * a / b:.1f}" if b else "—"
pp = lambda x: "0.0" if round(x, 1) == 0 else f"{x:+.1f}".replace("-", "−")
n_pop = {p: sum(r["population"] == p for r in POST.values()) for p in DIMS}
n_pop26 = {p: sum(r["population"] == p and r["year"] == YEAR for r in POST.values()) for p in DIMS}
Y = [x for x in LAB if x[5] == YEAR]
rep = lambda rows: (sum(x[2] != "unstated" and changed(x) for x in rows), sum(x[2] != "unstated" for x in rows))   # (first values replaced, first values)

NA, NW = "no attacker: operator harm or model failure (misplaced record)", "none: conventional exploit record misplaced in WITH-AI"
drop5 = {"ON-AI": sum(r["population"] == "ON-AI" and r["entry_point_post"] == NA for r in POST.values()),
         "WITH-AI": sum(r["population"] == "WITH-AI" and r["ai_role_post"] in (NA, NW) for r in POST.values())}
L = ["# Step 6 — Pre vs current vs 2026: what the review changed", "",
     "Generated by `s06_compare.py` (`make s06`); do not edit by hand. `out/dataset_pre.csv` and `out/dataset_post.csv` are written by `s04_methodology.py`.", "",
     "Three views of the same labels. *Pre* = the first value, from step 4's keyword rules or the corpus attack-vector label, 'unstated' where neither gave one (`out/dataset_pre.csv`). "
     "*Current* = the reviewed value reported in step 4 (`out/dataset_post.csv`). "
     f"*{YEAR}* = the current value for the {sum(r['year'] == YEAR for r in POST.values()):,} records dated {YEAR} (`out/dataset_post_{YEAR}.csv`; the corpus year is often the ingestion year, Table 1.5). "
     f"These tables keep every ON-AI and WITH-AI record (n = {n_pop['ON-AI']:,} and {n_pop['WITH-AI']:,}), as step 5 does; {drop5['ON-AI']} ON-AI and {drop5['WITH-AI']} WITH-AI records are ones "
     f"the review could not place as attacks (no attacker, or a conventional-exploit record misplaced in WITH-AI).", "",
     "Per-record values and how each was set: `out/dataset_post.csv` (columns in the README).", "", READ]

# ---------------------------------------------------------------- one table per population
def first_part(rows):
    r = rep(rows); un = sum(x[2] == "unstated" for x in rows)
    return f"review replaced {pc(*r)}% of {r[1]:,} first values; {pc(un, len(rows))}% started unstated"
for k, (pop, dims) in enumerate(DIMS.items(), 1):
    rows = [x for x in LAB if x[0] in dims]; r_all, r_y = rep(rows), rep([x for x in rows if x[5] == YEAR])
    L += ["", f"**Table 6.{k}. {pop}: the review replaced {pc(*r_all)}% of the first values ({YEAR}: {pc(*r_y)}%)** (n = {n_pop[pop]:,} records; {YEAR}: {n_pop26[pop]:,})", "",
          ("Rows grouped by dimension, values by current share. The dimension row gives, for all years and for 2026, the share of first values the review replaced and the share of labels "
           "that had no first value ('unstated', filled by a later rule, the coders or the review). *Change* = current − pre, from the shares as printed. "
           "— in the pre column = no first value was ever this one (it comes only from the later steps). "
           "*other* = an adversary is described but no value fits; *other (tracker stub, no system named)* = a pointer to an external tracker that names no attacked system. "
           "The no-attacker records appear under both dimensions; within a dimension the rows add to 100%." if k == 1 else "Columns as in Table 6.1."), "",
          f"| value | pre % | current % | change (points) | {YEAR} current % |", "|---|---|---|---|---|"]
    for d in dims:
        dr = [x for x in rows if x[0] == d]; dy = [x for x in dr if x[5] == YEAR]
        L.append(f"| **{NAME[d]}** (all years: {first_part(dr)}; {YEAR}: {first_part(dy)}) | | | | |")
        c0 = collections.Counter(x[2] for x in dr); c1 = collections.Counter(x[3] for x in dr); cy = collections.Counter(x[3] for x in dy)
        for v in sorted(set(c0) | set(c1), key=lambda v: (v == "unstated", -c1[v], v)):
            a0, a1, b1 = round(100 * c0[v] / len(dr), 1), round(100 * c1[v] / len(dr), 1), round(100 * cy[v] / len(dy), 1)
            L.append(f"| {v} | {'—' if not c0[v] else f'{a0:.1f}'} | {a1:.1f} | {pp(a1 - a0)} | {b1:.1f} |")

# ---------------------------------------------------------------- worked examples, by population
EXAMPLES = {   # (id, dimension): each was checked by two further independent reviewers, one told to argue for the original label; all agreed with the current one
    "ON-AI": [("INC-15866", "entry_point"), ("INC-00898", "entry_point"), ("INC-02870", "entry_point"), ("INC-03607", "target")],
    "WITH-AI": [("INC-04816", "ai_role"), ("INC-00512", "ai_role"), ("INC-00675", "ai_role"), ("INC-09141", "objective")]}
FLOW = collections.Counter((x[0], x[2], x[3]) for x in LAB if changed(x)); FLOW26 = collections.Counter((x[0], x[2], x[3]) for x in Y if changed(x))
def before_review(i, d):
    c = RNOTE.get((i, d)); m = METH[i]
    return (c["from"], m.get(d + "_pre_how", m[d + "_how"])) if c else (m[d], m[d + "_how"])
def story(i, d):
    r = POST[i]; pre, cur = r[d + "_pre"], r[d + "_post"]; b, bhow = before_review(i, d); c = RNOTE.get((i, d)); s = []
    assert pre != cur, f"{i} {d}: example no longer changes between pre and current"
    if PRE[i][d + "_source"] == "text rule": s.append(f"Pre: the keyword rule matched “{METH[i][d + '_match']}”, giving '{pre}'.")
    elif PRE[i][d + "_source"] == "corpus label": s.append(f"Pre: no keyword matched; the corpus label '{r['attack_vector']}' gave '{pre}'.")
    else:
        s.append("Pre: unstated.")
        if bhow == "label-group rule": s.append(f"A later rule set '{b}'" + (" because the description is a tracker stub." if d == "target" else f" from the corpus label '{r['attack_vector']}'."))
        elif bhow == "coded from text": s.append(f"The coders labelled it '{b}'.")
    s.append(f"Current: '{cur}'. Why: {c['note'].removeprefix('consistency: ').rstrip('.')}." if c else f"Current: '{cur}', kept by the review.")
    return " ".join(s)
L += ["", "## Why labels changed: worked examples", "",
      "Each example illustrates one of the common moves; the count is how many labels made the same move (all years / 2026). The reasons are the reviewers' own notes."]
n = 0
for pop, exs in EXAMPLES.items():
    L += ["", f"**{pop}**", ""]
    for i, d in exs:
        r = POST[i]; n += 1; key = (d, r[d + "_pre"], r[d + "_post"])
        t = r["title"] if len(r["title"]) <= 100 else r["title"][:97] + "…"
        L += [f"{n}. *{NAME[d]}: {key[1]} → {key[2]}* ({FLOW[key]:,} / {FLOW26[key]:,} labels). **{i}** ({r['channel']}, {r['year']}), *{t}*  ", "   " + story(i, d), ""]

# ---------------------------------------------------------------- summary (every number computed here, changes from the shares as printed)
RESID = {NA, NW, "other", "other (tracker stub, no system named)", "unstated"}
DROPPED = {i for i, r in POST.items() if (r["population"] == "ON-AI" and r["entry_point_post"] == NA) or (r["population"] == "WITH-AI" and r["ai_role_post"] in (NA, NW))}
def sh_(rows, v, col): return round(100 * sum(x[col] == v for x in rows) / len(rows), 1)
def moves(pop):
    """Per dimension: the attack value whose share rose most and the one that fell most, pre → current; misplaced-record values and 'unstated' left out.
    A value the rules never assign is described as such; a rise that comes mostly from records step 5 drops is said so."""
    out = []
    for d in DIMS[pop]:
        dr = [x for x in LAB if x[0] == d]; c0 = collections.Counter(x[2] for x in dr)
        vs = [v for v in {x[3] for x in dr} | set(c0) if v not in RESID]
        dlt = {v: sh_(dr, v, 3) - sh_(dr, v, 2) for v in vs}; up = max(vs, key=dlt.get); dn = min(vs, key=dlt.get)
        part = (f"{up}, a value the first rules never give, now holds {sh_(dr, up, 3):.1f}%" if not c0[up] else f"{up} rose {dlt[up]:.1f} points")
        from_drop = round(100 * (sum(x[1] in DROPPED and x[3] == up for x in dr) - sum(x[1] in DROPPED and x[2] == up for x in dr)) / len(dr), 1)
        if from_drop >= dlt[up] / 2: part += f" ({from_drop:.1f} points of it from records the review could not place as attacks)"
        part += f"; {dn} fell {abs(dlt[dn]):.1f} points"
        out.append(f"{NAME[d]}: {part}")
    return ". ".join(out)
def gap26(pop):
    """Per dimension: the value whose 2026 current share differs most from its all-years current share."""
    out = []
    for d in DIMS[pop]:
        dr = [x for x in LAB if x[0] == d]; dy = [x for x in dr if x[5] == YEAR]
        v = max({x[3] for x in dr}, key=lambda v: abs(sh_(dy, v, 3) - sh_(dr, v, 3)))
        out.append(f"{v} {sh_(dy, v, 3):.1f}% vs {sh_(dr, v, 3):.1f}%")
    return "; ".join(out)
def cvesh(pop, yr=None): rs = [r for r in POST.values() if r["population"] == pop and (yr is None or r["year"] == yr)]; return 100 * sum(r["channel"] == "cve/ghsa" for r in rs) / len(rs)
on_na = sh_([x for x in LAB if x[0] == "entry_point"], NA, 3); wi_na = sh_([x for x in LAB if x[0] == "ai_role"], NA, 3); wi_nw = sh_([x for x in LAB if x[0] == "ai_role"], NW, 3)
r_on, r_on26 = rep([x for x in LAB if x[0] in DIMS["ON-AI"]]), rep([x for x in Y if x[0] in DIMS["ON-AI"]])
r_wi, r_wi26 = rep([x for x in LAB if x[0] in DIMS["WITH-AI"]]), rep([x for x in Y if x[0] in DIMS["WITH-AI"]])
L += ["## What the comparison says", "",
      f"- The review replaced {pc(*r_on)}% of the ON-AI first values ({YEAR}: {pc(*r_on26)}%) and {pc(*r_wi)}% of the WITH-AI ones ({YEAR}: {pc(*r_wi26)}%): in both populations the {YEAR} records needed as much correction as all years.",
      f"- ON-AI: {on_na:.1f}% of records turned out to describe no attacker. {moves('ON-AI')} (Table 6.1).",
      f"- WITH-AI: {wi_na:.1f}% describe no attacker and {wi_nw:.1f}% are conventional-exploit records misplaced in WITH-AI. {moves('WITH-AI')} (Table 6.2).",
      f"- {YEAR} vs all years, current values, largest gap per dimension: ON-AI {gap26('ON-AI')}; WITH-AI {gap26('WITH-AI')}. {YEAR} ON-AI records lean toward the cve/ghsa channel "
      f"({cvesh('ON-AI', YEAR):.0f}% against {cvesh('ON-AI'):.0f}% for all years), which holds most conventional exploits and agent targets (Tables 4.1–4.2). None of these gaps is a trend: "
      f"the record year is often the ingestion year.",
      "- The examples show three things a keyword cannot tell: whether a word names the attack or only its impact or context ('credential', 'prompt injection', 'impersonate' in a CVE); "
      "whether a product or entity name is the thing attacked or produced ('GPT-4'; the AI Incident Database's 'Synthetic Audio' tag); and whether a corpus label ('deepfake') fits a story "
      "that states its medium or describes no attack."]
write("s06_compare.md", L)
print(f"replaced {pc(*rep(LAB))}% of first values ({YEAR}: {pc(*rep(Y))}%); examples {n}")
